<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Adarshas-MacBook-Pro.local" name="net.project.testClasses.HackerrankForWork.CodePair.SanityTestClass" tests="2" failures="0" timestamp="10 Jul 2015 09:50:15 GMT" time="1436521856.000" errors="1">
  <testcase name="codePairSanityTest1" time="1436521856.000" classname="net.project.testClasses.HackerrankForWork.CodePair.SanityTestClass"/>
  <testcase name="codePairSanityTest2" time="0.000" classname="net.project.testClasses.HackerrankForWork.CodePair.SanityTestClass">
    <error type="org.testng.TestNGException" message="
The data provider is trying to pass 2 parameters but the method net.project.testClasses.HackerrankForWork.CodePair.SanityTestClass#codePairSanityTest2 takes 4 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 2 parameters but the method net.project.testClasses.HackerrankForWork.CodePair.SanityTestClass#codePairSanityTest2 takes 4 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1265)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1136)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1263)
	... 17 more
]]>
    </error>
  </testcase> <!-- codePairSanityTest2 -->
</testsuite> <!-- net.project.testClasses.HackerrankForWork.CodePair.SanityTestClass -->
